import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/ThemeProvider";
import Main from "@/components/Main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={cn("h-dvh w-full")}>
        <ThemeProvider defaultTheme="light">
          <Main className="w-full h-full grid grid-rows-[auto_1fr] bg-background text-foreground">
            {children}
          </Main>
        </ThemeProvider>
      </body>
    </html>
  );
}
